import { Card } from "@/components/ui";
import { cn } from "@/utils";
import type { ReactNode } from "react";

interface SummaryCardProps {
  summary: string;
  className?: string;
}

const renderMarkdownSections = (summary: string): ReactNode => {
  const sections = summary.split(/^## /m).filter(Boolean);

  if (sections.length <= 1) {
    return <p className="whitespace-pre-wrap text-sm leading-relaxed text-slate-700">{summary}</p>;
  }

  return (
    <div className="space-y-6">
      {sections.map((section) => {
        const [heading, ...bodyParts] = section.split("\n");
        const body = bodyParts.join("\n").trim();

        return (
          <section key={heading}>
            <h3 className="text-sm font-semibold text-slate-900">{heading.trim()}</h3>
            <div className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-slate-700">
              {body}
            </div>
          </section>
        );
      })}
    </div>
  );
};

export const SummaryCard = ({ summary, className }: SummaryCardProps) => {
  return (
    <Card title="AI Summary" description="Generated by GPT-4o-mini" className={cn(className)}>
      {summary ? (
        renderMarkdownSections(summary)
      ) : (
        <p className="text-sm text-slate-500">No summary available yet.</p>
      )}
    </Card>
  );
};
